//! Single turn within a conversation session.
//!
//! A [`Turn`] represents one complete cycle from when the user sends a
//! message to when the agent produces a final response (or gives up). It
//! accumulates all messages, tool calls, and token usage for that cycle.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use vornix_providers::ChatMessage;
use vornix_tools::{ToolCall, ToolResult};

use crate::state::AgentState;

// ─── Token usage ─────────────────────────────────────────────────────────────

/// Token usage accounting for a single turn.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TurnUsage {
    /// Tokens sent to the model (prompt).
    pub input_tokens: u32,
    /// Tokens generated by the model (completion).
    pub output_tokens: u32,
    /// Tokens read from the provider's prompt cache.
    pub cached_read_tokens: u32,
    /// Estimated cost in USD for this turn.
    pub estimated_cost: f64,
}

impl TurnUsage {
    /// Total tokens consumed (input + output).
    pub fn total(&self) -> u32 {
        self.input_tokens + self.output_tokens
    }
}

// ─── Turn ────────────────────────────────────────────────────────────────────

/// A single agent turn — from user message to final agent response.
#[derive(Debug, Clone)]
pub struct Turn {
    /// Unique identifier for this turn.
    pub id: Uuid,
    /// The session this turn belongs to.
    pub session_id: Uuid,
    /// The agent's state within this turn (tracks lifecycle).
    pub state: AgentState,
    /// All messages generated during this turn (assistant text, tool results,
    /// intermediate reasoning, etc.).
    pub messages: Vec<ChatMessage>,
    /// Tool calls issued and their results, in order.
    pub tool_calls: Vec<(ToolCall, ToolResult)>,
    /// When the turn started processing.
    pub started_at: Option<DateTime<Utc>>,
    /// When the turn finished.
    pub ended_at: Option<DateTime<Utc>>,
    /// Cumulative token usage for this turn.
    pub token_usage: TurnUsage,
}

impl Turn {
    /// Create a new turn in the `Idle` state, not yet started.
    pub fn new(session_id: Uuid) -> Self {
        Self {
            id: Uuid::new_v4(),
            session_id,
            state: AgentState::Idle,
            messages: Vec::new(),
            tool_calls: Vec::new(),
            started_at: None,
            ended_at: None,
            token_usage: TurnUsage::default(),
        }
    }

    /// Mark the turn as started. Returns the start timestamp.
    pub fn start(&mut self) -> DateTime<Utc> {
        let now = Utc::now();
        self.started_at = Some(now);
        self.state = AgentState::Planning;
        now
    }

    /// Mark the turn as finished. Returns the end timestamp.
    pub fn finish(&mut self) -> DateTime<Utc> {
        let now = Utc::now();
        self.ended_at = Some(now);
        self.state = AgentState::Idle;
        now
    }

    /// Append a message to the turn's message list.
    pub fn add_message(&mut self, msg: ChatMessage) {
        self.messages.push(msg);
    }

    /// Record a tool call and its result.
    pub fn add_tool_call(&mut self, call: ToolCall, result: ToolResult) {
        self.tool_calls.push((call, result));
    }

    /// Update the cumulative token usage.
    pub fn update_usage(&mut self, input: u32, output: u32, cached: u32, cost: f64) {
        self.token_usage.input_tokens += input;
        self.token_usage.output_tokens += output;
        self.token_usage.cached_read_tokens += cached;
        self.token_usage.estimated_cost += cost;
    }

    /// Total wall-clock duration of the turn in milliseconds, or `None` if
    /// the turn hasn't finished yet.
    pub fn total_duration_ms(&self) -> Option<i64> {
        match (self.started_at, self.ended_at) {
            (Some(start), Some(end)) => Some((end - start).num_milliseconds()),
            _ => None,
        }
    }

    /// Number of tool calls executed in this turn.
    pub fn tool_call_count(&self) -> usize {
        self.tool_calls.len()
    }

    /// Returns `true` if the turn has been started.
    pub fn is_started(&self) -> bool {
        self.started_at.is_some()
    }

    /// Returns `true` if the turn has been finished.
    pub fn is_finished(&self) -> bool {
        self.ended_at.is_some()
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use vornix_providers::{MessageContent, Role};

    #[test]
    fn new_turn_is_idle() {
        let turn = Turn::new(Uuid::new_v4());
        assert_eq!(turn.state, AgentState::Idle);
        assert!(turn.messages.is_empty());
        assert!(turn.tool_calls.is_empty());
        assert!(turn.started_at.is_none());
        assert!(turn.ended_at.is_none());
        assert!(!turn.is_started());
        assert!(!turn.is_finished());
    }

    #[test]
    fn start_sets_state_and_time() {
        let mut turn = Turn::new(Uuid::new_v4());
        let start = turn.start();
        assert_eq!(turn.state, AgentState::Planning);
        assert!(turn.is_started());
        assert_eq!(turn.started_at, Some(start));
    }

    #[test]
    fn finish_sets_state_and_time() {
        let mut turn = Turn::new(Uuid::new_v4());
        turn.start();
        let end = turn.finish();
        assert_eq!(turn.state, AgentState::Idle);
        assert!(turn.is_finished());
        assert_eq!(turn.ended_at, Some(end));
    }

    #[test]
    fn duration_calculation() {
        let mut turn = Turn::new(Uuid::new_v4());
        assert_eq!(turn.total_duration_ms(), None);

        turn.start();
        assert_eq!(turn.total_duration_ms(), None); // not finished

        turn.finish();
        let ms = turn.total_duration_ms().unwrap();
        assert!(ms >= 0);
    }

    #[test]
    fn add_message() {
        let mut turn = Turn::new(Uuid::new_v4());
        turn.add_message(ChatMessage {
            role: Role::User,
            content: MessageContent::Text("hello".to_string()),
            tool_call_id: None,
            tool_calls: None,
            reasoning_content: None,
        });
        assert_eq!(turn.messages.len(), 1);
    }

    #[test]
    fn add_tool_call() {
        let mut turn = Turn::new(Uuid::new_v4());
        let call = ToolCall::new("test", serde_json::json!({}));
        let result = ToolResult::success(&call, "ok", 50);
        turn.add_tool_call(call, result);
        assert_eq!(turn.tool_call_count(), 1);
    }

    #[test]
    fn usage_accumulates() {
        let mut turn = Turn::new(Uuid::new_v4());
        turn.update_usage(100, 50, 20, 0.01);
        turn.update_usage(200, 100, 40, 0.02);
        assert_eq!(turn.token_usage.input_tokens, 300);
        assert_eq!(turn.token_usage.output_tokens, 150);
        assert_eq!(turn.token_usage.cached_read_tokens, 60);
        assert!((turn.token_usage.estimated_cost - 0.03).abs() < f64::EPSILON);
    }
}
